### ISSUE TITLE
`Cluster.launch` doesn't like `count` of 1

### ISSUE THREAD

**Issue by cmillion** [MillionConcepts/killscreen#2]
```
---------------------------------------------------------------------------
TimeoutError                              Traceback (most recent call last)
Cell In[14], line 2
      1 #cluster = Cluster.launch(2, template='a_template', key='a_key.pem')
----> 2 cluster = Cluster.launch(1, template='a_template', key='a_key.pem')

File ~/github/hostess/hostess/aws/ec2.py:570, in Cluster.launch(cls, count, template, options, tags, client, session, wait, *instance_args, **instance_kwargs)
    568         if "does not exist" in str(ce):
    569             time.sleep(0.2)
--> 570     raise TimeoutError(
    571         "launched instances successfully, but unable to run "
    572         "DescribeInstances. Perhaps permissions are wrong."
    573     )
    574 cluster = Cluster(instances)
    575 cluster.fleet_request = fleet

TimeoutError: launched instances successfully, but unable to run DescribeInstances. Perhaps permissions are wrong.
```

But `Cluster.launch(2, ....` works fine. Assume that this is related to encoding an idea of a "cluster" as n>1. But not the behavior I would expect for n=1.

**Comment by cmillion** [comment]
Ok... I take this back somewhat. Sometimes this works and sometimes it does not. Investigating.

**Comment by m-stclair** [comment]
this is intended to work and i have used it fairly extensively. if you can identify the case in which it does not, that would be helpful.

**Comment by m-stclair** [comment]
as background, the reason `launch` is only implemented on `Cluster` and not `Instance` is not a conceptual decision as such, but an isomorphism with the AWS API. there is no unique API operation to create a single instance: there are _only_ fleet requests. Creating a single instance requires issuing a fleet request for a number of instances equal to 1. We could of course create syntactic sugar for this to implement an `Instance.launch` method -- some portions of the `Cluster.launch` functionality would then want to move to shared code outside the classes.

**Comment by cmillion** [comment]
I understand. Thank you for the clarification.

I think that the error that I was getting was due to other factors. Closing this for now.
