### ISSUE TITLE
Checking "status" (vs. "state") of ec2 instances

### ISSUE THREAD

**Issue by cmillion** [MillionConcepts/killscreen#4]
The AWS ec2 dashboard has a parameter column for "Status Check" which reads as "initializing" until the machine is fully booted (and then reads "2/2 checks passed"). Is there a way for us to check against this in `hostess` in order to know when the machine is fully ready?

**Comment by m-stclair** [comment]
yes, but you probably don't want it. The 'Initializing' status can persist until many separate on-boot background processes have completed -- including ones that use almost no system resources -- and, moreover, status checks occur at most once per minute. An instance is generally ready for use long before 'Initializing' changes to 'Ready', sometimes up to 5 minutes before.

**Comment by m-stclair** [comment]
The functional intent of this feature request is fulfilled by the wait-until-connectable features added in 53a0423. Specifically, the `Instance` and `Cluster` `launch()` and `start()` methods now accept the  `connect` kwarg. Passing `connect=True` ensures that the calling thread blocks until commands can be executed on the instance(s).
